name = "linktree"
main = "cloudflare/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Use site bucket for static files (simpler approach)
[site]
bucket = "build/client"

[[routes]]
pattern = "linktree.ialannunez.mx"
zone_name = "ialannunez.mx"
